### ISSUE TITLE
Please give a simple setup instruction

### ISSUE THREAD

**Issue by bgewehr** [Sineos/Push-Volkszaehler-Readings-to-Influxdb-via-MQTT#1]
Hi Sineos,

I'd like to use your flow but I am total starter in the node thing.

Could you please put a simple setup instruction into the readme?

Thank you very much!

Kind regards
Bernd

**Comment by Sineos** [comment]
Thanks for your interest. I improved the readme instructions

**Comment by bgewehr** [comment]
Wow. That helped me instantly to find my error. Was the additional lines in volkszaehler.conf.php for the websocket that were missing. Should be directly in the standard config, shouldn't it?

**Comment by Sineos** [comment]
It is in the conf.template.php. See https://github.com/volkszaehler/volkszaehler.org/blob/master/etc/volkszaehler.conf.template.php
I guess the problem is that an existing installation does not use the template, so it is easy to miss

**Comment by bgewehr** [comment]
I see. Thank you!
